language: python
python:
  - "3.7.4"
matrix:
  include:
    - name: "Python 3.7.4 with Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - python -m pytest